language: android
sudo: false

env:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

jdk:
  - oraclejdk7

android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

script:
  - ./gradlew check

notifications:
  slack:
    - secure: "BzgcvZOuMECr71qk3IJdCzDaMh9fhHjzZt37gRNxtsle0v93jWIzjBhjEd9xOH/CMXIw9EEHyQ6bqt2oUtRZqM1sUDEFLLPW6fuFg8m29TkZ11/zOubg3/nsq0uDDwXxCfB6bTG5RDjTmSTb85ZqENl1ES5aUgdMbGhfWV/zzL4MwDpiF0m+cpwwTV5I36basIxl4SQA15g+OXV6I7qFP8Us2fNWAbinLNgkQrI9E7oiHD5w7RnbnSFT0upBBiqDPVeW14NodajtE670Cmthcg+512Su51Ezbz4PGKE8+PDg4Jz1sJ9a1F3KkORi37Ol/cywhXL2H+5uSBkWXJFVuYKPDXyLAAXfz/j23x1954vtKOQ814J/TS6knc836eYyMY7hgKaMFDTA2ntwy2Cf7A7sX/euP/HpIv6rqLmXC5PZqeCuFtVzBzy4fpWw82JLiwrVSgw7/AMKvU4bSjJF8gGby3V8wdHL3ckZLPx5DXEGanfkHtcwYenKB/QavQVfsfC84J3jOp4wqS5alf3Ta6wA73UPezxX4/cs8QzLfNthq1H3SD5k/3RaxUgS2Z95ZyUKHHEoYxTqY15CjLAUHrbFsx8HZ+d7Hek3fFksuM9zdFAlRxvOs7NwNArVN61CBIB5315/AEU1n8gvaiWL0R4wOFA4zmyEq/Ap8Txw6+k="
