language: android
sudo: false

jdk:
  - oraclejdk7

android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

script:
  - ./gradlew check
